### ISSUE TITLE
Getting error: setting a property that has only a getter

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#182]
As reported here: https://gitter.im/canjs/canjs?at=5903464bcfec919272839c87

Still working on finding an example that shows the problem

**Comment by phillipskevin** [comment]
This didn't fix the issue.

**Comment by roemhildtg** [comment]
This is failing for me:

```html
<script src="./node_modules/steal/steal.js" main="@loader">
import DefineMap from 'can-define/map/map';

export const Filter = DefineMap.extend('Filter', {
    value: {
        type: '*'
    },
    name: {
        type: 'string',
        get (name) {
            return name || 'test';
        },
        serialize (name) {
            return name;
        }
    },
    operator: {
        type: 'string',
        value: 'like'
    }
});

console.log(new Filter({
      name: 'test',
      operator: 'equals',
      value: 'test'
}));
</script>
```

```
steal.js:7194 TypeError: Cannot set property operator of #<Object> which has only a getter
    at Filter.eval (can-define.js:283)
    at Filter.eval (can-define.js:294)
    at Filter.eval [as operator] (can-define.js:416)
    at String.eval (can-define.js:720)
    at each (each.js:41)
    at Filter.define.setup (can-define.js:718)
    at Filter.setup (map.js:99)
    at Function.newInstance (can-construct.js:289)
    at Filter.init (can-construct.js:637)
    at new Filter (eval at <anonymous> (can-construct.js:NaN), <anonymous>:3:29) "TypeError: Cannot set property operator of #<Object> which has only a getter
    at Filter.eval (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-define/can-define.js:283:22)
    at Filter.eval (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-define/can-define.js:294:14)
    at Filter.eval [as operator] (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-define/can-define.js:416:17)
    at String.eval (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-define/can-define.js:720:14)
    at each (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-util/js/each/each.js:41:16)
    at Filter.define.setup (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-define/can-define.js:718:2)
    at Filter.setup (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-define/map/map.js:99:18)
    at Function.newInstance (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-construct/can-construct.js:289:22)
    at Filter.init (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-construct/can-construct.js:637:29)
    at new Filter (eval at <anonymous> (http://greggtest.cityhall.com/gis/static_apps/spectre-can-js/node_modules/can-construct/can-construct.js), <anonymous>:3:29)"
```

**Comment by bmomberger-bitovi** [comment]
The minimal breaking example is to extend a  DefineMap with a value property, and overwrite that property in the props object when constructing.

from the console:
```
> System.import("can-define/map/").then(c => DefineMap = c)
> Foo = DefineMap.extend({ "bar" : { value : "baz" } });
> new Foo({ bar: "quux" }) // => boom
```

The object with the get-only property is `_data` on the constructed object, and it's meant to be temporary.  It's set by `can-define.replaceWith` temporarily, to be replaced by a value property definition on first read.  When constructing, the prop is being set on `_data` without first reading the property and replacing the definition, so it breaks.

This doesn't occur in CanJS 3.5.1, so that can be used as a baseline for comparison.

**Comment by justinbmeyer** [comment]
I wonder if the fix here is to do a Object.defineProperty instead of a prop set.
