### ISSUE TITLE
Default value results in an error

### ISSUE THREAD

**Issue by ilyavf** [canjs/can-define#206]
Component's view model has a property with a default value:
```js
const ViewModel = DefineMap.extend({
  myProp: {
    value: "default value"
  }
})
```
In template I am passing a new value for the property:
```html
<my-component my-prop="new value" />
```
The following error gets thrown:
```
Potentially unhandled rejection [1] TypeError: Cannot set property myProp of #<Object> which has only a getter
    at DefineMap.eval (http://localhost:8081/node_modules/can-define/can-define.js:283:22)
    at DefineMap.eval (http://localhost:8081/node_modules/can-define/can-define.js:294:14)
    at DefineMap.make.set.type [as myProp] (http://localhost:8081/node_modules/can-define/can-define.js:416:17)
    at String.eval (http://localhost:8081/node_modules/can-define/can-define.js:720:14)
    at each (http://localhost:8081/node_modules/can-util/js/each/each.js:41:16)
    at DefineMap.define.setup (http://localhost:8081/node_modules/can-define/can-define.js:718:2)
    at DefineMap.setup (http://localhost:8081/node_modules/can-define/map/map.js:99:18)
    at Function.newInstance (http://localhost:8081/node_modules/can-construct/can-construct.js:289:22)
    at DefineMap.init (http://localhost:8081/node_modules/can-construct/can-construct.js:637:29)
    at new DefineMap (eval at <anonymous> (http://localhost:8081/node_modules/can-construct/can-construct.js)
```

**Comment by ilyavf** [comment]
This might be related more to can-component...

**Comment by phillipskevin** [comment]
This seems to work ok in JSBin: http://jsbin.com/kivikozeho/1/edit?html,js,output. Can you see anything different from what you're doing?

**Comment by ilyavf** [comment]
@phillipskevin Thanks for the jsbin. The bug occured for me because I used `can-define@1.0.18`.

I just noticed:
```
warning can-define@1.0.18: Use 1.0.20 or later to avoid a DefineMap intialization bug
```

So, looks like it was fixed.
