### ISSUE TITLE
The current version of can-define is broken

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-define#216]
this comes when hitting current done-serve if can-define 1.2.0 is used or any pre 
1.0.26 is working
```
done-serve starting on http://localhost:8080
Received client connection
Live-reload server listening on port 8012
TypeError: name argument is required to req.get
    at IncomingMessage.header (/home/frank/workspace/peep/artist/node_modules/express/lib/request.js:67:11)
    at Object.getValue (file:/home/frank/workspace/peep/artist/node_modules/can-define/define-helpers/define-helpers.js:92:19)
    at IncomingMessage.<anonymous> (file:/home/frank/workspace/peep/artist/node_modules/can-define/define-helpers/define-helpers.js:139:29)
    at eachDefinition (file:/home/frank/workspace/peep/artist/node_modules/can-define/map/map.js:28:11)
    at DefineMap.forEach (file:/home/frank/workspace/peep/artist/node_modules/can-define/map/map.js:268:4)
    at Object.defineHelpers.serialize (file:/home/frank/workspace/peep/artist/node_modules/can-define/define-helpers/define-helpers.js:128:8)
    at DefineMap.get (file:/home/frank/workspace/peep/artist/node_modules/can-define/map/map.js:178:25)
    at Object.getValue (file:/home/frank/workspace/peep/artist/node_modules/can-reflect/reflections/get-set/get-set.js:150:20)
    at getFastPathRoot (file:/home/frank/workspace/peep/artist/node_modules/can-view-scope/compute_data.js:36:22)
    at ScopeKeyData.<anonymous> (file:/home/frank/workspace/peep/artist/node_modules/can-view-scope/compute_data.js:127:22)

```

**Comment by justinbmeyer** [comment]
Please provide more information. The error looks like it's in req.get, not in define.

**Comment by frank-dspeed** [comment]
@justinbmeyer installation of can-define@1.0.26 fixes it all 
its from the can-reflect update yesterday

**Comment by matthewp** [comment]
Here `req` is a Node.js request object, which does have a .get() method which takes an argument. can-define is trying to call it like a definemap .get(), which is the problem. I'm working on a test.

**Comment by matthewp** [comment]
I added a breaking test in 838ad1019c39a9a0c17189fdf2d3d51a8a56e71f
