### ISSUE TITLE
get fails if DefineMap contains a Map

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define#224]
The code below will fail with the error
```
TypeError: val[how] is not a function
	    at Object.getValue (http://localhost/can-reflect-test-app/node_modules/can-define/define-helpers/define-helpers.js:89:19)
	    at Map.eval (http://localhost/can-reflect-test-app/node_modules/can-define/define-helpers/define-helpers.js:136:29)
	    at eachDefinition (http://localhost/can-reflect-test-app/node_modules/can-define/map/map.js:29:11)
	    at DefineMap.forEach (http://localhost/can-reflect-test-app/node_modules/can-define/map/map.js:269:4)
	    at Object.defineHelpers.serialize (http://localhost/can-reflect-test-app/node_modules/can-define/define-helpers/define-helpers.js:125:8)
	    at DefineMap.get (http://localhost/can-reflect-test-app/node_modules/can-define/map/map.js:179:25)
```

```js
var CanMap = require('can-map');
var DefineMap = require('can-define/map/map');

var myMap = new DefineMap({
  foo: new CanMap()
});

myMap.get();
```

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-define/pull/225.
